services:
  meal-guides-mailer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meal-guides-mailer-service
    ports:
      - "7002:7002"
    networks:
      - the-meal-guides-network
    restart: unless-stopped
    environment:
      - TZ=Asia/Manila
networks:
  the-meal-guides-network:
    driver: bridge